[package]
name = "aoc_22"
version = "0.1.0"
edition = "2021"
author = "Ryan M"
default-run = "aoc_22"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
itertools = "0.11"

[term]
quiet = true
