[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
author = "Ryan M"

default-run = "aoc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"

[term]
quiet = true
