[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
author = "Ryan M"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[term]
quiet = true